drop table if exists zepto;     

CREATE TABLE ZEPTO(
SKU_ID SERIAL PRIMARY KEY,             --Creates auto-increment unique ID.
CATEGORY VARCHAR(120),
NAME VARCHAR(150) NOT NULL,
MRP NUMERIC (8,2),                              -- TOTAL 8 DIGITS ,2 DIGITS AFTER DECIMAL (EX 9999.99)
DISCOUNTPERCENT NUMERIC (5,2),
AVAILABLEQUANTITY INT,
DISCOUNTEDSELLINGPRICE NUMERIC(8,2),
WEIGHTINGRAMS INT,
OUTOFSTOCK BOOLEAN,                          --TRUE - OUTOF STK  FALSE- AVAILABLE
QUANTITY INT
);

--DATA EXPLORATION
COMMIT;
SELECT COUNT(*) FROM ZEPTO;

SELECT * FROM ZEPTO
LIMIT 10;

-- nullvalues
SELECT * FROM ZEPTO
WHERE NAME IS NULL
OR
CATEGORY IS NULL
OR
MRP IS NULL
OR
DISCOUNTPERCENT IS NULL
OR
AVAILABLEQUANTITY IS NULL
OR
DISCOUNTEDSELLINGPRICE IS NULL
OR
WEIGHTINGRAMS IS NULL
OR
OUTOFSTOCK IS NULL
OR
QUANTITY IS NULL;

-- DIFFERENT PRODUCT CATEGORY
SELECT DISTINCT CATEGORY FROM ZEPTO
ORDER BY CATEGORY ;

-- PDT IN STOCK VS OUT OF STOCK
SELECT OUTOFSTOCK ,COUNT(SKU_ID) AS NUMBER FROM ZEPTO
GROUP BY OUTOFSTOCK;

--Which product names appear multiple times in the dataset.
SELECT  NAME, COUNT(SKU_ID) AS "NO OF SKUs"
FROM ZEPTO
GROUP BY NAME
HAVING COUNT(SKU_ID)>1
ORDER BY COUNT(SKU_ID) DESC;

--DATA CLEANING

-- PRODUCT  WITH PRICE =0
SELECT * FROM ZEPTO
WHERE MRP = 0 OR DISCOUNTEDSELLINGPRICE = 0;

-- DELETE 
DELETE FROM ZEPTO
WHERE MRP = 0;

--CONVERT PAISA TO RUPEE
UPDATE ZEPTO
SET MRP = MRP/100.0,
DISCOUNTEDSELLINGPRICE = DISCOUNTEDSELLINGPRICE/100.0;

SELECT MRP,DISCOUNTEDSELLINGPRICE FROM ZEPTO;


-- Q1. Find the top 10 best-value products based on the discount percentage.
SELECT DISTINCT NAME, MRP, DISCOUNTPERCENT
FROM ZEPTO
ORDER BY DISCOUNTPERCENT DESC
LIMIT 10;


-- Q2.What are the Products with High MRP but Out of Stock
SELECT DISTINCT NAME, MRP
FROM ZEPTO
WHERE MRP > 300 AND OUTOFSTOCK IS TRUE
ORDER BY MRP DESC;

-- Q3.Calculate Estimated Revenue for each category
SELECT CATEGORY,
SUM(DISCOUNTEDSELLINGPRICE * AVAILABLEQUANTITY) AS TOTAL_REVENUE
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY TOTAL_REVENUE;

-- Q4. Find all products where MRP is greater than ₹500 and discount is less than 10%.
SELECT  DISTINCT NAME, MRP, DISCOUNTPERCENT
FROM ZEPTO	
WHERE MRP > 500 AND DISCOUNTPERCENT <  10
ORDER BY MRP DESC, DISCOUNTPERCENT DESC;


-- Q5. Identify the top 5 categories offering the highest average discount percentage.
SELECT DISTINCT CATEGORY,
ROUND(AVG(DISCOUNTPERCENT),2) AS AVG_DISCOUNT
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY AVG_DISCOUNT DESC
LIMIT 5;

-- Q6. Find the price per gram for products above 100g and sort by best value.
SELECT DISTINCT name, WEIGHTINGRAMS, discountedSellingPrice,
ROUND(discountedSellingPrice/WEIGHTINGRAMS,2) AS price_per_gram
FROM zepto
WHERE WEIGHTINGRAMS >= 100
ORDER BY price_per_gram;

-- Q7.Group the products into categories like Low, Medium, Bulk.
SELECT NAME , WEIGHTINGRAMS,
CASE
WHEN WEIGHTINGRAMS < 1000 THEN 'LOW'
WHEN WEIGHTINGRAMS BETWEEN 1000 AND 5000 THEN 'MEDIUM'
ELSE 'BULK'
END AS WEIGHT_CATEGORY	
FROM ZEPTO;


-- Q8.What is the Total Inventory Weight Per Category
SELECT category,
SUM(WEIGHTINGRAMS * availableQuantity) AS total_weight
FROM zepto
GROUP BY category
ORDER BY total_weight;




















